///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MultipleTestsuites
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MultipleTestsuitesRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("f199aa88-a136-4351-a04d-3c0a33209083")]
    public partial class MultipleTestsuitesRepository : RepoGenBaseFolder
    {
        static MultipleTestsuitesRepository instance = new MultipleTestsuitesRepository();
        MultipleTestsuitesRepositoryFolders.ApplicationUnderTestAppFolder _applicationundertest;

        /// <summary>
        /// Gets the singleton class instance representing the MultipleTestsuitesRepository element repository.
        /// </summary>
        [RepositoryFolder("f199aa88-a136-4351-a04d-3c0a33209083")]
        public static MultipleTestsuitesRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MultipleTestsuitesRepository() 
            : base("MultipleTestsuitesRepository", "/", null, 0, false, "f199aa88-a136-4351-a04d-3c0a33209083", ".\\RepositoryImages\\MultipleTestsuitesRepositoryf199aa88.rximgres")
        {
            _applicationundertest = new MultipleTestsuitesRepositoryFolders.ApplicationUnderTestAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("f199aa88-a136-4351-a04d-3c0a33209083")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ApplicationUnderTest folder.
        /// </summary>
        [RepositoryFolder("331cf5f7-4dcf-4089-88dc-d209b240e201")]
        public virtual MultipleTestsuitesRepositoryFolders.ApplicationUnderTestAppFolder ApplicationUnderTest
        {
            get { return _applicationundertest; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MultipleTestsuitesRepositoryFolders
    {
        /// <summary>
        /// The ApplicationUnderTestAppFolder folder.
        /// </summary>
        [RepositoryFolder("331cf5f7-4dcf-4089-88dc-d209b240e201")]
        public partial class ApplicationUnderTestAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _functionaluitestautomationwithintelInfo;
            RepoItemInfo _ranorexInfo;
            RepoItemInfo _productsInfo;
            RepoItemInfo _solutionsInfo;

            /// <summary>
            /// Creates a new ApplicationUnderTest  folder.
            /// </summary>
            public ApplicationUnderTestAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ApplicationUnderTest", "/dom[@domain='www.ranorex.com']", parentFolder, 30000, null, false, "331cf5f7-4dcf-4089-88dc-d209b240e201", "")
            {
                _functionaluitestautomationwithintelInfo = new RepoItemInfo(this, "FunctionalUITestAutomationWithIntel", ".//div[#'main-content']/article/div/div/div/div[1]/div/div[1]/div[1]/?/?/h1[@innertext>'Functional UI Test Automation']", ".//div[#'main-content']//h1[@innertext>'Functional UI Test Automation']", 30000, null, "e961ff41-ae80-4cb8-8ed4-114d44c4a1c1");
                _ranorexInfo = new RepoItemInfo(this, "Ranorex", ".//div[#'page-container']/div[@id='et-boc']/header/div/div[2]//a[@href='https://www.ranorex.com/']/?/?/img[@title='Ranorex-Logo-WithTagline']", ".//div[#'et-boc']//img[@title='Ranorex-Logo-WithTagline']", 30000, null, "a0b97386-2b4d-452f-aac0-69bc4b4dd429");
                _productsInfo = new RepoItemInfo(this, "Products", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Products']", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Products']", 30000, null, "b214010f-0de8-4a81-9e62-1c06707cdacd");
                _solutionsInfo = new RepoItemInfo(this, "Solutions", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Solutions']", ".//ul[#'menu-main-mega-menu']/?/?/a[@innertext='Solutions']", 30000, null, "2e406f02-7555-44d2-95ff-9dd6ea7e3cc6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("331cf5f7-4dcf-4089-88dc-d209b240e201")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("331cf5f7-4dcf-4089-88dc-d209b240e201")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The FunctionalUITestAutomationWithIntel item.
            /// </summary>
            [RepositoryItem("e961ff41-ae80-4cb8-8ed4-114d44c4a1c1")]
            public virtual Ranorex.H1Tag FunctionalUITestAutomationWithIntel
            {
                get
                {
                    return _functionaluitestautomationwithintelInfo.CreateAdapter<Ranorex.H1Tag>(true);
                }
            }

            /// <summary>
            /// The FunctionalUITestAutomationWithIntel item info.
            /// </summary>
            [RepositoryItemInfo("e961ff41-ae80-4cb8-8ed4-114d44c4a1c1")]
            public virtual RepoItemInfo FunctionalUITestAutomationWithIntelInfo
            {
                get
                {
                    return _functionaluitestautomationwithintelInfo;
                }
            }

            /// <summary>
            /// The Ranorex item.
            /// </summary>
            [RepositoryItem("a0b97386-2b4d-452f-aac0-69bc4b4dd429")]
            public virtual Ranorex.ImgTag Ranorex
            {
                get
                {
                    return _ranorexInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The Ranorex item info.
            /// </summary>
            [RepositoryItemInfo("a0b97386-2b4d-452f-aac0-69bc4b4dd429")]
            public virtual RepoItemInfo RanorexInfo
            {
                get
                {
                    return _ranorexInfo;
                }
            }

            /// <summary>
            /// The Products item.
            /// </summary>
            [RepositoryItem("b214010f-0de8-4a81-9e62-1c06707cdacd")]
            public virtual Ranorex.ATag Products
            {
                get
                {
                    return _productsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Products item info.
            /// </summary>
            [RepositoryItemInfo("b214010f-0de8-4a81-9e62-1c06707cdacd")]
            public virtual RepoItemInfo ProductsInfo
            {
                get
                {
                    return _productsInfo;
                }
            }

            /// <summary>
            /// The Solutions item.
            /// </summary>
            [RepositoryItem("2e406f02-7555-44d2-95ff-9dd6ea7e3cc6")]
            public virtual Ranorex.ATag Solutions
            {
                get
                {
                    return _solutionsInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Solutions item info.
            /// </summary>
            [RepositoryItemInfo("2e406f02-7555-44d2-95ff-9dd6ea7e3cc6")]
            public virtual RepoItemInfo SolutionsInfo
            {
                get
                {
                    return _solutionsInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
